load("//bazel:build_defs.bzl", "congelado_module_library")

congelado_module_library(
    name = "utils_buffering",
    primary_interface = "base.cppm",
    partitions = [
        "deleter.cppm",
        "writter.cppm",
        "reader.cppm",
        "node.cppm",
        "view.cppm",
    ],
    visibility = ["//visibility:public"],
)
