load("//bazel:build_defs.bzl", "congelado_module_library")

congelado_module_library(
    name = "hashmap",
    primary_interface = "base.cppm",
    partitions = [
        "swiss.cppm",
    ],
    visibility = ["//visibility:public"],
)
