load("//bazel:build_defs.bzl", "congelado_module_library")

congelado_module_library(
    name = "cc",
    primary_interface = "cc.cppm",
    deps = [
        "//include/cc/abi:cc_abi",
    ],
    visibility = ["//visibility:public"],
)
