export module utils_codec:atom;

import std;

export namespace utils::codec {

template <std::ranges::view Inner, std::unsigned_integral UInt = std::uint32_t>
    requires std::ranges::forward_range<Inner>
class BigEndianView : public std::ranges::view_interface<BigEndianView<Inner, UInt>> {
  public:
    struct Iterator {
        using base_iterator = std::ranges::iterator_t<Inner>;
        using iterator_category = std::forward_iterator_tag;
        using iterator_concept = std::forward_iterator_tag;
        using value_type = std::ranges::range_value_t<Inner>;
        using difference_type = std::ranges::range_difference_t<Inner>;
        using pointer = const value_type *;
        using reference = value_type;

        /**
         * @brief Default ctor, builds a zeroed/uninitialized iterator (position defaults matter
         * more than the value here since equality only checks `m_pos`).
         */
        Iterator() = default;
        /**
         * @brief Builds an iterator over `val`, starting at byte position `pos`.
         * @param val the integer whose bytes get walked.
         * @param pos the starting byte position (0 = most significant byte).
         */
        Iterator(UInt val, std::size_t pos = 0) : m_val{val}, m_pos{pos} {}

        // Convetring the current 8 bits of the value into the format directed by the view before it (e.g., std::byte)
        // and return it
        /**
         * @brief Extracts the byte at the current position, most-significant-byte-first.
         * @return the current position's byte, shifted and cast to `value_type`.
         */
        reference operator*() const { return static_cast<value_type>(m_val >> (8 * (sizeof(UInt) - 1 - m_pos))); }

        // Advance the iterator underlying iterator by one byte and advance the position by one byte
        /**
         * @brief Advances to the next byte position. Bet, that's the whole increment.
         * @return `*this`, advanced.
         */
        Iterator &operator++() {
            ++m_pos;
            return *this;
        }

        // Some views/algorithms (like std::ranges::take) call post-increment
        /**
         * @brief Postfix advance — copies the current state out before stepping forward.
         * @return the iterator's state before this call.
         */
        Iterator operator++(int) {
            Iterator temp = *this;
            ++(*this);
            return temp;
        }

        // Only equal is need the not equal is automatically generated by the compiler
        /**
         * @brief Equality check against the end sentinel — done once every byte of `UInt` has
         * been walked.
         * @return true if the current position has reached `sizeof(UInt)`.
         */
        bool operator==(std::default_sentinel_t /*unused*/) const { return m_pos >= sizeof(UInt); }

        // Only equal is need the not equal is automatically generated by the compiler
        /**
         * @brief Equality check against another iterator.
         * @param other the iterator to compare against.
         * @return true if both are at the same byte position.
         */
        bool operator==(const Iterator &other) const { return m_pos == other.m_pos; }

      private:
        UInt m_val;
        std::size_t m_pos = 0;
    };

    /**
     * @brief Default ctor, zero-valued view.
     */
    BigEndianView() = default;
    /**
     * @brief Wraps `val` for big-endian byte iteration.
     * @param val the integer to serialize.
     */
    explicit BigEndianView(UInt val) : m_val{val} {}

    /**
     * @brief Start of the byte sequence.
     * @return an iterator at the most significant byte.
     */
    [[nodiscard]] constexpr Iterator begin() const { return Iterator{m_val}; }
    /**
     * @brief End of the byte sequence.
     * @return the sentinel-equivalent iterator, positioned past the last byte.
     */
    [[nodiscard]] constexpr Iterator end() const { return Iterator{m_val, sizeof(UInt)}; }

  private:
    UInt m_val;
};

/**
 * @brief CTAD deduction guide — lets `BigEndianView{range, val}` deduce `Inner` from whatever
 * viewable range gets passed, wrapped through `std::views::all_t`.
 * @tparam R the viewable range being deduced from.
 * @tparam UInt the unsigned integer type being serialized.
 */
template <std::ranges::viewable_range R, std::unsigned_integral UInt>
BigEndianView(R, UInt) -> BigEndianView<std::views::all_t<R>, UInt>;

template <std::unsigned_integral UInt = std::uint32_t>
struct WriteBigEndianAdaptor : std::ranges::range_adaptor_closure<WriteBigEndianAdaptor<UInt>> {
    /**
     * @brief Binds the adaptor to the value it'll serialize. Bet — nothing happens till this gets
     * piped or invoked.
     * @param val the integer to serialize when invoked.
     */
    explicit constexpr WriteBigEndianAdaptor(UInt val) : m_val{val} {}

    /**
     * @brief No-range overload — just yields the standalone big-endian byte view for `m_val`,
     * nothing to concatenate onto.
     * @return a `BigEndianView` over `m_val` with an empty byte range as its base.
     */
    constexpr auto operator()() const { return BigEndianView<std::ranges::empty_view<std::byte>, UInt>{m_val}; }

    /**
     * @brief Concatenates `m_val`'s big-endian bytes onto the tail of `range`.
     * @tparam R the viewable range being piped in.
     * @param range the range to append the serialized bytes onto.
     * @return `range` followed by `m_val`'s big-endian byte sequence.
     */
    template <std::ranges::viewable_range R>
    constexpr auto operator()(R &&range) const {
        return std::views::concat(std::forward<R>(range), BigEndianView<std::views::all_t<R>, UInt>{m_val});
    }

    UInt m_val;
};

template <std::unsigned_integral UInt = std::uint32_t>
struct ReadBigEndianAdaptor : std::ranges::range_adaptor_closure<ReadBigEndianAdaptor<UInt>> {
    /**
     * @brief Default ctor, no state to bind — the value being read comes from whatever range gets
     * piped in at call time.
     */
    explicit constexpr ReadBigEndianAdaptor() = default;

    /**
     * @brief Folds `data`'s bytes left-to-right into a single `UInt`, most-significant byte
     * first.
     * @tparam R the viewable range of bytes being decoded.
     * @param data the byte range to fold into an integer.
     * @throws std::runtime_error if `data` has more bytes than `UInt` can hold — that's a hard L,
     * no silent truncation happening here.
     * @return the decoded big-endian integer, or 0 if `data` is empty.
     */
    template <std::ranges::viewable_range R>
    UInt operator()(R &&data) const {
        std::size_t dist = std::ranges::distance(data);

        // Hard L if the caller hands over more bytes than `UInt` can hold — no silent truncation.
        if (dist > sizeof(UInt)) {
            throw std::runtime_error(
                std::format("Too many bytes ({}) to fit into {}-byte integer", dist, sizeof(UInt)));
        }

        // Nothing to fold, bail with zero.
        if (dist == 0) {
            return UInt{0};
        }

        // Fold left, most-significant byte first: shift what's accumulated so far up by a byte
        // and OR the next one in.
        return std::ranges::fold_left(std::forward<R>(data), UInt{0}, [](UInt acc, std::byte byte_value) {
            return static_cast<UInt>((acc << 8) | std::to_integer<std::uint8_t>(byte_value));
        });
    }
};

template <std::ranges::view Inner, std::unsigned_integral UInt = std::uint32_t>
    requires std::ranges::forward_range<Inner>
class VariantEndianView : public std::ranges::view_interface<VariantEndianView<Inner, UInt>> {
  public:
    static constexpr std::uint64_t LIMIT_6BIT = 64;          // 2^6
    static constexpr std::uint64_t LIMIT_14BIT = 16384;      // 2^14
    static constexpr std::uint64_t LIMIT_30BIT = 1073741824; // 2^30

    struct Iterator {
        using base_iterator = std::ranges::iterator_t<Inner>;
        using iterator_category = std::forward_iterator_tag;
        using iterator_concept = std::forward_iterator_tag;
        using value_type = std::ranges::range_value_t<Inner>;
        using difference_type = std::ranges::range_difference_t<Inner>;
        using pointer = const value_type *;
        using reference = value_type;

        /**
         * @brief Default ctor, builds a zeroed/uninitialized iterator.
         */
        Iterator() = default;
        /**
         * @brief Builds an iterator over `val`, already resolved to `length` bytes with prefix
         * bits `prefix`, starting at byte position `pos`.
         * @param val the integer whose bytes get walked.
         * @param length how many bytes the encoding resolved to (1, 2, 4, or 8).
         * @param prefix the 2-bit length-class prefix baked into byte 0's top bits.
         * @param pos the starting byte position.
         */
        Iterator(UInt val, std::size_t length, std::uint8_t prefix = 0, std::size_t pos = 0)
            : m_val{val}, m_length{length}, m_prefix{prefix}, m_pos{pos} {}

        // Convetring the current 8 bits of the value into the format directed by the view before it (e.g., std::byte)
        // and return it
        /**
         * @brief Extracts the byte at the current position. Position 0 gets the length prefix
         * OR'd into its top 2 bits, everything after is a plain big-endian byte of `m_val`.
         * @return the current position's byte, prefix-tagged if it's byte 0.
         */
        reference operator*() const {
            // Byte 0 carries the 2-bit length-class prefix OR'd into its top bits — everything
            // after that is just a plain big-endian byte of `m_val`.
            if (m_pos == 0) {
                return static_cast<value_type>((m_val >> (8 * (m_length - 1))) | (m_prefix << 6));
            }
            return static_cast<value_type>(m_val >> (8 * (m_length - 1 - m_pos)));
        }

        // Advance the iterator underlying iterator by one byte and advance the position by one byte
        /**
         * @brief Advances to the next byte position.
         * @return `*this`, advanced.
         */
        Iterator &operator++() {
            ++m_pos;
            return *this;
        }

        // Some views/algorithms (like std::ranges::take) call post-increment
        /**
         * @brief Postfix advance — copies the current state out before stepping forward.
         * @return the iterator's state before this call.
         */
        Iterator operator++(int) {
            Iterator temp = *this;
            ++(*this);
            return temp;
        }

        // Only equal is need the not equal is automatically generated by the compiler
        /**
         * @brief Equality check against the end sentinel — done once `m_length` bytes have been
         * walked.
         * @return true if the current position has reached `m_length`.
         */
        bool operator==(std::default_sentinel_t /*unused*/) const { return m_pos >= m_length; }

        // Only equal is need the not equal is automatically generated by the compiler
        /**
         * @brief Equality check against another iterator.
         * @param other the iterator to compare against.
         * @return true if both are at the same byte position.
         */
        bool operator==(const Iterator &other) const { return m_pos == other.m_pos; }

      private:
        UInt m_val;
        std::size_t m_length = 0;
        std::size_t m_pos = 0;
        std::uint8_t m_prefix = 0;
    };

    /**
     * @brief Default ctor, zero-valued view.
     */
    VariantEndianView() = default;
    /**
     * @brief Wraps `val`, resolving its length class (and prefix) up front via encoding().
     * @param val the integer to serialize.
     */
    explicit VariantEndianView(UInt val) : m_val{val} {
        auto [prefix, length] = encoding(val);
        m_length = length;
        m_prefix = prefix;
    }

    /**
     * @brief Start of the encoded byte sequence.
     * @return an iterator at byte 0 (the prefix-tagged byte).
     */
    constexpr Iterator begin() const { return Iterator{m_val, m_length, m_prefix, 0}; }
    /**
     * @brief End of the encoded byte sequence.
     * @warning Passes `sizeof(UInt)` as the sentinel iterator's position, not `m_length` — happens
     * to still compare correctly since Iterator's equality only checks `m_pos == other.m_pos` and
     * this end iterator is only ever compared for equality, never dereferenced. Still a little
     * sus that it doesn't just reuse `m_length` here like begin() does with position 0.
     * @return the sentinel-equivalent iterator, positioned past the last encoded byte.
     */
    constexpr Iterator end() const { return Iterator{m_val, m_length, m_prefix, sizeof(UInt)}; }

  private:
    /**
     * @brief Picks the length class for `val` — smaller values get shorter encodings. Mirrors the
     * classic 2-bit-prefix varint scheme: under 2^6 fits in 1 byte (prefix 0), under 2^14 in 2
     * bytes (prefix 1), under 2^30 in 4 bytes (prefix 2), anything bigger gets the full 8 bytes
     * (prefix 3). No L taken on huge values, they just cost more bytes.
     * @param val the value to classify.
     * @return the `{prefix, length}` pair for `val`'s size class.
     */
    static constexpr std::pair<std::uint8_t, std::size_t> encoding(UInt val) {
        // Classic 2-bit-prefix varint ladder — smaller values fall through fewer checks and land
        // in a shorter encoding. No L taken on huge values, they just cost more bytes.
        if (val < LIMIT_6BIT) {
            return {0x00, 1};
        }
        if (val < LIMIT_14BIT) {
            return {0x01, 2};
        }
        if (val < LIMIT_30BIT) {
            return {0x02, 4};
        }
        return {0x03, 8};
    }

    UInt m_val;
    std::size_t m_length = 0;
    std::uint8_t m_prefix = 0;
};


/**
 * @brief CTAD deduction guide for `VariantEndianView`, same deal as `BigEndianView`'s.
 * @tparam R the viewable range being deduced from.
 * @tparam UInt the unsigned integer type being serialized.
 */
template <std::ranges::viewable_range R, std::unsigned_integral UInt>
VariantEndianView(R, UInt) -> VariantEndianView<std::views::all_t<R>, UInt>;

template <std::unsigned_integral UInt = std::uint32_t>
struct WriteVariantEndianAdaptor : std::ranges::range_adaptor_closure<WriteVariantEndianAdaptor<UInt>> {
    /**
     * @brief Binds the adaptor to the value it'll serialize.
     * @param val the integer to serialize when invoked.
     */
    explicit constexpr WriteVariantEndianAdaptor(UInt val) : m_val{val} {}

    /**
     * @brief No-range overload — just yields the standalone variable-length byte view for
     * `m_val`.
     * @return a `VariantEndianView` over `m_val` with an empty byte range as its base.
     */
    constexpr auto operator()() const { return VariantEndianView<std::ranges::empty_view<std::byte>, UInt>{m_val}; }

    /**
     * @brief Concatenates `m_val`'s variable-length-encoded bytes onto the tail of `range`.
     * @tparam R the viewable range being piped in.
     * @param range the range to append the serialized bytes onto.
     * @return `range` followed by `m_val`'s variable-length byte sequence.
     */
    template <std::ranges::viewable_range R>
    constexpr auto operator()(R &&range) const {
        return std::views::concat(std::forward<R>(range), VariantEndianView<std::views::all_t<R>, UInt>{m_val});
    }

    UInt m_val;
};

template <std::unsigned_integral UInt = std::uint32_t>
struct ReadVariantEndianAdaptor : std::ranges::range_adaptor_closure<ReadVariantEndianAdaptor<UInt>> {
    /**
     * @brief Default ctor, no state to bind.
     */
    explicit constexpr ReadVariantEndianAdaptor() = default;

    /**
     * @brief Reads the first byte to figure out the length class from its top 2 bits, then folds
     * the remaining `length - 1` bytes (plus the low 6 bits of byte 0) into the decoded integer.
     * @warning Assumes `data` actually has at least `length` bytes available once the prefix is
     * read — feed it a truncated range and it's reading garbage/UB territory past the end, this
     * adaptor doesn't check. Don't be that guy shipping a truncated buffer into this.
     * @tparam R the viewable range of bytes being decoded.
     * @param data the byte range to decode, prefix byte first.
     * @return the decoded integer.
     */
    template <std::ranges::viewable_range R>
    UInt operator()(R &&data) const {
        // Peel off byte 0 first — its top 2 bits say how many bytes the whole value spans (1, 2,
        // 4, or 8, via the `1 << prefix` trick).
        std::uint8_t first = data | std::views::take(1) | ReadBigEndianAdaptor<std::uint8_t>{};
        std::uint8_t prefix = (first >> 6) & 0x03;
        std::size_t length = 1UZ << prefix;

        // Fold the remaining `length - 1` bytes in on top of byte 0's low 6 bits (the actual
        // value bits, prefix stripped off).
        return std::ranges::fold_left(
            std::forward<R>(data) | std::views::drop(1) | std::views::take(length - 1), static_cast<UInt>(first & 0x3F),
            [](UInt acc, auto byte_value) { return static_cast<UInt>((acc << 8) | std::to_integer<std::uint8_t>(byte_value)); });
    }
};

} // namespace utils::codec
