export module utils_codec:atom;

import std;

export namespace utils::codec {

template <std::ranges::view Inner, std::unsigned_integral UInt = std::uint32_t>
    requires std::ranges::forward_range<Inner>
class BigEndianView : public std::ranges::view_interface<BigEndianView<Inner, UInt>> {
  public:
    struct Iterator {
        using base_iterator = std::ranges::iterator_t<Inner>;
        using iterator_category = std::forward_iterator_tag;
        using iterator_concept = std::forward_iterator_tag;
        using value_type = std::ranges::range_value_t<Inner>;
        using difference_type = std::ranges::range_difference_t<Inner>;
        using pointer = const value_type *;
        using reference = value_type;

        Iterator() = default;
        Iterator(UInt val, std::size_t pos = 0) : m_val{val}, m_pos{pos} {}

        // Convetring the current 8 bits of the value into the format directed by the view before it (e.g., std::byte)
        // and return it
        reference operator*() const { return static_cast<value_type>(m_val >> (8 * (sizeof(UInt) - 1 - m_pos))); }

        // Advance the iterator underlying iterator by one byte and advance the position by one byte
        Iterator &operator++() {
            ++m_pos;
            return *this;
        }

        // Some views/algorithms (like std::ranges::take) call post-increment
        Iterator operator++(int) {
            Iterator temp = *this;
            ++(*this);
            return temp;
        }

        // Only equal is need the not equal is automatically generated by the compiler
        bool operator==(std::default_sentinel_t) const { return m_pos >= sizeof(UInt); }

        // Only equal is need the not equal is automatically generated by the compiler
        bool operator==(const Iterator &other) const { return m_pos == other.m_pos; }

      private:
        UInt m_val;
        std::size_t m_pos;
    };

    BigEndianView() = default;
    explicit BigEndianView(UInt val) : m_val{val} {}

    constexpr Iterator begin() const { return Iterator{m_val}; }
    constexpr Iterator end() const { return Iterator{m_val, sizeof(UInt)}; }

  private:
    UInt m_val;
};

template <std::ranges::viewable_range R, std::unsigned_integral UInt>
BigEndianView(R, UInt) -> BigEndianView<std::views::all_t<R>, UInt>;

template <std::unsigned_integral UInt = std::uint32_t>
struct WriteBigEndianAdaptor : std::ranges::range_adaptor_closure<WriteBigEndianAdaptor<UInt>> {
    explicit constexpr WriteBigEndianAdaptor(UInt val) : m_val{val} {}

    constexpr auto operator()() const { return BigEndianView<std::ranges::empty_view<std::byte>, UInt>{m_val}; }

    template <std::ranges::viewable_range R>
    constexpr auto operator()(R &&range) const {
        return std::views::concat(std::forward<R>(range), BigEndianView<std::views::all_t<R>, UInt>{m_val});
    }

    UInt m_val;
};

template <std::unsigned_integral UInt = std::uint32_t>
struct ReadBigEndianAdaptor : std::ranges::range_adaptor_closure<ReadBigEndianAdaptor<UInt>> {
    explicit constexpr ReadBigEndianAdaptor() {}

    template <std::ranges::viewable_range R>
    UInt operator()(R &&data) const {
        std::size_t dist = std::ranges::distance(data);

        if (dist > sizeof(UInt)) {
            throw std::runtime_error(
                std::format("Too many bytes ({}) to fit into {}-byte integer", dist, sizeof(UInt)));
        }

        if (dist == 0) {
            return UInt{0};
        }

        return std::ranges::fold_left(std::forward<R>(data), UInt{0}, [](UInt acc, std::byte b) {
            return static_cast<UInt>((acc << 8) | std::to_integer<std::uint8_t>(b));
        });
    }
};

template <std::ranges::view Inner, std::unsigned_integral UInt = std::uint32_t>
    requires std::ranges::forward_range<Inner>
class VariantEndianView : public std::ranges::view_interface<VariantEndianView<Inner, UInt>> {
  public:
    static constexpr std::uint64_t LIMIT_6BIT = 64;          // 2^6
    static constexpr std::uint64_t LIMIT_14BIT = 16384;      // 2^14
    static constexpr std::uint64_t LIMIT_30BIT = 1073741824; // 2^30

    struct Iterator {
        using base_iterator = std::ranges::iterator_t<Inner>;
        using iterator_category = std::forward_iterator_tag;
        using iterator_concept = std::forward_iterator_tag;
        using value_type = std::ranges::range_value_t<Inner>;
        using difference_type = std::ranges::range_difference_t<Inner>;
        using pointer = const value_type *;
        using reference = value_type;

        Iterator() = default;
        Iterator(UInt val, std::size_t length, std::uint8_t prefix = 0, std::size_t pos = 0)
            : m_val{val}, m_length{length}, m_prefix{prefix}, m_pos{pos} {}

        // Convetring the current 8 bits of the value into the format directed by the view before it (e.g., std::byte)
        // and return it
        reference operator*() const {
            if (m_pos == 0) {
                return static_cast<value_type>((m_val >> (8 * (m_length - 1))) | (m_prefix << 6));
            }
            return static_cast<value_type>(m_val >> (8 * (m_length - 1 - m_pos)));
        }

        // Advance the iterator underlying iterator by one byte and advance the position by one byte
        Iterator &operator++() {
            ++m_pos;
            return *this;
        }

        // Some views/algorithms (like std::ranges::take) call post-increment
        Iterator operator++(int) {
            Iterator temp = *this;
            ++(*this);
            return temp;
        }

        // Only equal is need the not equal is automatically generated by the compiler
        bool operator==(std::default_sentinel_t /*unused*/) const { return m_pos >= m_length; }

        // Only equal is need the not equal is automatically generated by the compiler
        bool operator==(const Iterator &other) const { return m_pos == other.m_pos; }

      private:
        UInt m_val;
        std::size_t m_length;
        std::size_t m_pos;
        std::uint8_t m_prefix;
    };

    VariantEndianView() = default;
    explicit VariantEndianView(UInt val) : m_val{val} {
        auto [prefix, length] = encoding(val);
        m_length = length;
        m_prefix = prefix;
    }

    constexpr Iterator begin() const { return Iterator{m_val, m_length, m_prefix, 0}; }
    constexpr Iterator end() const { return Iterator{m_val, m_length, m_prefix, sizeof(UInt)}; }

  private:
    static constexpr std::pair<std::uint8_t, std::size_t> encoding(UInt val) {
        if (val < LIMIT_6BIT) {
            return {0x00, 1};
        }
        if (val < LIMIT_14BIT) {
            return {0x01, 2};
        }
        if (val < LIMIT_30BIT) {
            return {0x02, 4};
        }
        return {0x03, 8};
    }

    UInt m_val;
    std::size_t m_length;
    std::uint8_t m_prefix;
};


template <std::ranges::viewable_range R, std::unsigned_integral UInt>
VariantEndianView(R, UInt) -> VariantEndianView<std::views::all_t<R>, UInt>;

template <std::unsigned_integral UInt = std::uint32_t>
struct WriteVariantEndianAdaptor : std::ranges::range_adaptor_closure<WriteVariantEndianAdaptor<UInt>> {
    explicit constexpr WriteVariantEndianAdaptor(UInt val) : m_val{val} {}

    constexpr auto operator()() const { return VariantEndianView<std::ranges::empty_view<std::byte>, UInt>{m_val}; }

    template <std::ranges::viewable_range R>
    constexpr auto operator()(R &&range) const {
        return std::views::concat(std::forward<R>(range), VariantEndianView<std::views::all_t<R>, UInt>{m_val});
    }

    UInt m_val;
};

template <std::unsigned_integral UInt = std::uint32_t>
struct ReadVariantEndianAdaptor : std::ranges::range_adaptor_closure<ReadVariantEndianAdaptor<UInt>> {
    explicit constexpr ReadVariantEndianAdaptor() {}

    template <std::ranges::viewable_range R>
    UInt operator()(R &&data) const {
        std::uint8_t first = data | std::views::take(1) | ReadBigEndianAdaptor<std::uint8_t>{};
        std::uint8_t prefix = (first >> 6) & 0x03;
        std::size_t length = 1uz << prefix;

        return std::ranges::fold_left(
            std::forward<R>(data) | std::views::drop(1) | std::views::take(length - 1), static_cast<UInt>(first & 0x3F),
            [](UInt acc, auto b) { return static_cast<UInt>((acc << 8) | std::to_integer<std::uint8_t>(b)); });
    }
};

} // namespace utils::codec
