load("//bazel:build_defs.bzl", "congelado_module_library")

congelado_module_library(
    name = "utils_codec",
    primary_interface = "codec.cppm",
    partitions = [
        "atom.cppm",
    ],
    visibility = ["//visibility:public"],
)
