load("//bazel:build_defs.bzl", "congelado_module_library")

congelado_module_library(
    name = "cc_utils_kernel",
    partitions = [
        "fd.cppm",
    ],
    primary_interface = "base.cppm",
    visibility = ["//visibility:public"],
)
