-- Generates and builds a small binary that exposes selected sdk/ classes to Python/Lua, via
-- core::ffi::Exported<T> specializations (include/core/ffi/ffi.cppm) + FfiRuntime::register_class
-- (include/core/manager/ffi.cppm).
--
-- No C++26 static reflection on this toolchain (__cpp_reflection is undefined, no experimental
-- flag enables it either), so a type can't be auto-enumerated by the compiler — instead, a type
-- opts in by hand-writing a core::ffi::Exported<T> specialization (mirroring how
-- serde::Serializable<T> already opts a type into FieldDesc-based serialization), and this
-- script "auto-discovers" every opted-in type by scanning sdk/**.cppm source text for the
-- "core::ffi::Exported<...>" marker — nothing else needs to know about a newly-exported type
-- up front, dropping the specialization is the whole opt-in.
--
-- TODO(reflection): this whole text-scanning discovery step is a stand-in for real reflection
-- (GCC 16.1 has working P2996 support via -freflection today, clang doesn't yet — see
-- include/core/ffi/ffi.cppm's TODO). Once register_class<T>() reflects over T directly again,
-- "discovery" stops needing a marker to grep for at all — this script (or its replacement)
-- would just need the list of types to expose, not a source-text scan to find them.
--
-- Everything below lives inside on_load, not at top-level description scope: io.readfile/
-- writefile are only reachable from a chunk that actually runs in script scope (on_load/
-- after_build-style callbacks) — a *local function* defined at this file's top level is
-- still compiled under the restricted description-scope environment even when later called
-- from inside on_load, so `io` reads as nil no matter where the call happens. Confirmed the
-- hard way; os.files()/path.join() work at either scope, file-content I/O doesn't.

target("congelado_sdk_ffi")
	set_kind("binary")
	set_languages("c++26")
	set_policy("build.c++.modules", true)
	add_includedirs("$(projectdir)/include")
	add_deps("congelado_sdk")
	-- No cpython/lua packages here: this binary never touches either language's C API directly
	-- anymore — running a script is fully delegated to whichever bridge plugin self-reports
	-- handling that file extension (see generate_registry_source() below). Only the bridge
	-- plugins themselves (plugins/bridge/python_bridge, plugins/bridge/lua_bridge) still link those.
	add_rpathdirs("$ORIGIN")
	if is_plat("linux", "macosx") then
		add_cxflags("-ffile-prefix-map=$(projectdir)=.", "-fmacro-prefix-map=$(projectdir)=.")
	end

	on_load(function (target)
		local function discover_ffi_exports()
			local exports = {}
			for _, f in ipairs(os.files(path.join(os.projectdir(), "sdk/**.cppm"))) do
				local content = io.readfile(f)
				-- Require the real specialization syntax ("struct ... Exported<X> {"), not
				-- just the bare substring — a stray comment mentioning the marker (like this
				-- file's own doc comments, or a future one) won't false-match.
				if content and content:find("struct core::ffi::Exported<", 1, true) then
					local module_name = content:match("export module ([%w_]+)")
					if module_name then
						for class_name in content:gmatch("struct core::ffi::Exported<(.-)>%s*{") do
							table.insert(exports, { class_name = class_name, module_name = module_name })
						end
					end
				end
			end
			return exports
		end

		local function generate_registry_source(exports)
			local seen_modules = { congelado_plugin = true, core_plugin = true, congelado_heart = true }
			local imports = { "import congelado_plugin;" }
			local calls = {}
			for _, export in ipairs(exports) do
				if not seen_modules[export.module_name] then
					seen_modules[export.module_name] = true
					table.insert(imports, "import " .. export.module_name .. ";")
				end
				-- Simple (unqualified) name for the Python/Lua-facing prefix —
				-- "congelado::worker::TaskRunner" becomes just "TaskRunner", since "::" isn't
				-- valid in either language's identifiers.
				local simple_name = export.class_name:match("([%w_]+)$") or export.class_name
				table.insert(calls, string.format(
					"    rt.register_class<%s>(cfg, \"%s\");", export.class_name, simple_name))
			end

			return string.format([[
// GENERATED by xmake/ffi.lua from sdk/**.cppm's core::ffi::Exported<T> specializations —
// do not edit by hand, this file is regenerated whenever xmake reconfigures.
#include <congelado/abi.h>
#include <cstdio>

import std;
import core_plugin;
import congelado_heart;
import interfaces;
%s

int main(int argc, char *argv[]) {
    congelado::FfiRuntime rt;
    congelado::GenerationConfig cfg;

    // Bridges are dlopen'd plugins now (plugins/bridge/python_bridge, plugins/bridge/lua_bridge, or any other
    // user-added one), not linkable classes — scan/open/build the plugins directory and feed
    // whatever bridges turn up straight into rt (the one FfiRuntime this binary uses for every
    // register_class<T>() call below), same resolve_bridge() the engine host uses. Which
    // runtimes cfg wants is derived from whatever actually loaded, not a hardcoded pair — this
    // binary never names "python"/"lua" anywhere; a bridge is identified purely by its own
    // runtime_name()/script_extension(). Same relative-to-binary path derivation
    // src/worker_main.cc uses, since this binary also lands under build/<plat>/<arch>/<mode>/
    // while the shared plugins directory lives at build/plugins.
    auto plugin_base = argc > 0 ? std::filesystem::path(argv[0]).parent_path() : std::filesystem::path{};
    auto plugins_dir = std::filesystem::path{std::format("{}/../../../plugins", plugin_base.string())};
    core::plugin::SharedLibrary bridge_store{"plugin"};
    bridge_store.scan(plugins_dir);
    if (auto open_res = bridge_store.open_all(); open_res) {
        CongeladoHostCallbacks empty_host_cb{};
        if (auto build_res = bridge_store.build(empty_host_cb, {}); build_res) {
            bridge_store.for_each([&rt, &cfg](const std::shared_ptr<core::plugin::FfiRuntime> &bridge_runtime) {
                auto plugin = bridge_runtime->get_plugin();
                if (!plugin) {
                    return;
                }
                if (auto bridge = congelado::heart::resolve_bridge(*plugin)) {
                    cfg.add_runtime(std::string{bridge->runtime_name()});
                    rt.add_bridge(std::move(bridge));
                }
            });
        } else {
            std::println(stderr, "[sdk_ffi] bridge plugin build failed: {}", build_res.error().get_message());
        }
    } else {
        std::println(stderr, "[sdk_ffi] bridge plugin load failed: {}", open_res.error().get_message());
    }

%s

    std::println("[sdk_ffi] {} FFI entries registered", rt.get_size());

    if (argc < 2) {
        std::println("usage: {} <script file>", argv[0]);
        return 0;
    }

    // No per-language branching here — ask each loaded bridge whether it handles this
    // extension (self-reported via script_extension()), then hand the whole run off to it.
    std::string_view script_path = argv[1];
    auto extension = std::filesystem::path(script_path).extension().string();
    auto *bridge = rt.find_bridge_for_extension(extension);
    if (bridge == nullptr) {
        std::println(stderr, "no bridge loaded for extension '{}'", extension);
        return 1;
    }
    return bridge->run_script(script_path);
}
]], table.concat(imports, "\n"), table.concat(calls, "\n"))
		end

		local exports = discover_ffi_exports()
		if #exports == 0 then
			-- Nothing opted in — disable rather than fail on a source-less target.
			target:set("enabled", false)
			return
		end

		local generated_dir = path.join(os.projectdir(), "sdk/ffi/generated")
		os.mkdir(generated_dir)
		local generated_file = path.join(generated_dir, "registry.cc")
		io.writefile(generated_file, generate_registry_source(exports))
		target:add("files", generated_file)
	end)
target_end()
