load("//bazel:build_defs.bzl", "congelado_module_library")

congelado_module_library(
    name = "cc_utils_pipe",
    primary_interface = "base.cppm",
    partitions = [
        "pipe.cppm",
        "fd.cppm",
        "process.cppm",
    ],
    visibility = ["//visibility:public"],
)
