// SYCL reference plugin — graph-level fusion pass: TFGrapplerOptimizerOps::optimize.
//
// Not built by Bazel (docs/ only). This is the OTHER fusion mechanism in this C ABI, distinct
// from the kernel-level oneDNN post-ops in kernels/matmul.cppm and kernels/conv.cppm: it rewrites
// the *graph* before any kernel runs, collapsing a Conv2D/Addmm/Bmm node followed by a BiasAdd
// (and optionally a Relu) into one node — bias becomes an extra input, and Relu becomes the
// node's own "activation" attribute (1 = relu), read by ConvKernel::create / MatmulKernel::create
// and applied as a oneDNN post-op at kernel-construction time. Graph-level rewrite and
// kernel-level post-op end up working together this way, rather than being two unrelated fusion
// paths.
//
// TFGrapplerOptimizerOps::optimize's TF_Buffer holds a serialized tensorflow::GraphDef — the real
// proto message, defined in include/cc/proto/{graph,node_def,attr_value}.proto and built by the
// proto_service rule in include/cc/proto/BUILD (graph.pb.h's GraphDef, node_def.pb.h's NodeDef,
// attr_value.pb.h's AttrValue). An earlier version of this file invented its own binary graph
// format instead, having missed that the real schema is vendored here — that was wrong; this
// version parses/rewrites the real GraphDef.
//
// Known gap: TFGrapplerItem's nodes-to-preserve / fetch-node lists are not consulted, so a node
// that must survive unmodified (e.g. a fetch/output node) could still be fused away — a real
// pass checks item.get_nodes_to_preserve_list()/get_fetch_nodes_list() first. Only 1:1 "producer
// feeds exactly one consumer" chains are matched; a BiasAdd or Relu with more than one consumer,
// or whose only input is not the conv/matmul node's sole output, is left alone.

module;

#include "include/c/extern/grappler/optimizer.h"
// Generated by the proto_service rule in include/cc/proto/BUILD from graph.proto/node_def.proto/
// attr_value.proto. Their own `import "cc/proto/...";` statements are what fixes this include
// path (no "include/" prefix) — it must match how protoc wires the generated headers together.
#include "cc/proto/attr_value.pb.h"
#include "cc/proto/graph.pb.h"
#include "cc/proto/node_def.pb.h"

export module sycl_backend:optimizer;

import std;
import cc_ice_extern_grappler_builder;
import cc_ice_intern_builder;

export namespace sycl_backend {

class SyclGrapplerOptimizer : public ice::builder::TFGrapplerOptimizer
{
public:
    SyclGrapplerOptimizer() = default;

    ~SyclGrapplerOptimizer() override = default;
    SyclGrapplerOptimizer(const SyclGrapplerOptimizer&) = delete;
    SyclGrapplerOptimizer& operator=(const SyclGrapplerOptimizer&) = delete;
    SyclGrapplerOptimizer(SyclGrapplerOptimizer&&) = delete;
    SyclGrapplerOptimizer& operator=(SyclGrapplerOptimizer&&) = delete;

    [[nodiscard]] std::expected<void, ice::sonic::Status> optimize(
        ice::builder::Buffer& graph_buf,
        ice::builder::TFGrapplerItem& item,
        ice::builder::Buffer& out_optimized_graph_buf
    ) noexcept override
    {
        (void)item;

        TFBufferData input_buffer{};
        graph_buf.get_buffer(&input_buffer);

        tensorflow::GraphDef graph_def;
        if (!graph_def.ParseFromArray(input_buffer.data, static_cast<int>(input_buffer.length))) {
            return std::unexpected{
                ice::sonic::Status::from_message("SyclGrapplerOptimizer: malformed GraphDef")
            };
        }

        tensorflow::GraphDef fused = fuse_bias_and_activation(graph_def);

        std::string bytes;
        if (!fused.SerializeToString(&bytes)) {
            return std::unexpected{ice::sonic::Status::from_message(
                "SyclGrapplerOptimizer: failed to serialize the rewritten GraphDef"
            )};
        }
        out_optimized_graph_buf.assign_from_string(bytes.data(), bytes.size());

        return {};
    }

private:
    static bool is_fusable_producer(const std::string& op) noexcept
    {
        return op == "Conv2D" || op == "Addmm" || op == "Bmm";
    }

    // How many other nodes read `producer_output` as an input. A producer whose output feeds
    // more than one consumer cannot be fused into that one consumer without changing the graph's
    // meaning for the others.
    static int
    count_consumers(const tensorflow::GraphDef& graph, const std::string& producer_output)
    {
        int count = 0;
        for (const tensorflow::NodeDef& node: graph.node()) {
            for (const std::string& input: node.input()) {
                if (input == producer_output) {
                    ++count;
                }
            }
        }
        return count;
    }

    static const tensorflow::NodeDef*
    find_node(const tensorflow::GraphDef& graph, const std::string& name)
    {
        for (const tensorflow::NodeDef& node: graph.node()) {
            if (node.name() == name) {
                return &node;
            }
        }
        return nullptr;
    }

    static const tensorflow::NodeDef*
    find_relu_consumer(const tensorflow::GraphDef& graph, const std::string& producer_output)
    {
        for (const tensorflow::NodeDef& node: graph.node()) {
            if (node.op() == "Relu" && node.input_size() == 1 && node.input(0) == producer_output) {
                return &node;
            }
        }
        return nullptr;
    }

    tensorflow::GraphDef fuse_bias_and_activation(const tensorflow::GraphDef& input) const
    {
        tensorflow::GraphDef output;
        *output.mutable_versions() = input.versions();
        *output.mutable_library() = input.library();

        std::set<std::string> absorbed;

        for (const tensorflow::NodeDef& node: input.node()) {
            if (absorbed.contains(node.name())) {
                continue;
            }

            if (node.op() != "BiasAdd") {
                *output.add_node() = node;
                continue;
            }

            // node is a BiasAdd. Its first input must be the sole output of a fusable producer,
            // and that producer's output must have exactly this one consumer.
            if (node.input_size() == 0) {
                *output.add_node() = node;
                continue;
            }

            const std::string& producer_name = node.input(0);
            const tensorflow::NodeDef* producer = find_node(input, producer_name);
            if (producer == nullptr || !is_fusable_producer(producer->op()) ||
                absorbed.contains(producer->name()) || count_consumers(input, producer_name) != 1) {
                *output.add_node() = node;
                continue;
            }

            tensorflow::NodeDef fused = *producer;
            if (node.input_size() > 1) {
                fused.add_input(node.input(1));
            }
            absorbed.insert(producer->name());

            // Is there a Relu reading BiasAdd's sole output, with no other consumer?
            if (count_consumers(input, node.name()) == 1) {
                const tensorflow::NodeDef* relu = find_relu_consumer(input, node.name());
                if (relu != nullptr) {
                    (*fused.mutable_attr())["activation"].set_i(1);
                    fused.set_name(relu->name());
                    absorbed.insert(relu->name());
                    *output.add_node() = std::move(fused);
                    continue;
                }
            }

            fused.set_name(node.name());
            *output.add_node() = std::move(fused);
        }

        return output;
    }
};

} // namespace sycl_backend
