load("//bazel:build_defs.bzl", "congelado_module_library")

congelado_module_library(
    name = "io_error",
    primary_interface = "error.cppm",
    partitions = [
        "base.cppm",
        "http.cppm",
    ],
    visibility = ["//visibility:public"],
)
