load("//bazel:build_defs.bzl", "congelado_cc_binary")

# XLA hello world — commented out (XLA dependency removed)
# congelado_cc_binary(
#     name = "openxla",
#     srcs = ["openxla.cc"],
#     deps = [
#         "//include/cc/stable_hlo:cc_stable_hlo",
#         "@xla//xla/pjrt/c:pjrt_c_api_cpu",
#         "@xla//xla/pjrt/c:pjrt_c_api_hdrs",
#     ],
# )
