load("//bazel:build_defs.bzl", "congelado_module_library")

congelado_module_library(
    name = "cc_utils_pipe",
    partitions = [
        # "pipe.cppm",
        # "fd.cppm",
        # "process.cppm",
    ],
    primary_interface = "base.cppm",
    visibility = ["//visibility:public"],
)
